export type LibraryCard = {
  it: string;
  en: string;
  example: string;
  tag: string;
  level: "A1" | "A2" | "B1" | "B2";
};

export const MISSION_TOPUP_PATCHES: Record<string, Partial<LibraryCard>> = {
  "il bagno": { example: "Il bagno e privato oppure condiviso?" },
  "la cucina": { example: "La cucina e condivisa con un altro inquilino." },
  "la visita": {
    en: "the apartment viewing",
    example: "Possiamo fissare una visita per domani pomeriggio?",
  },
  "l'appartamento": { example: "L'appartamento e vicino alla metro." },
  "la stanza": { example: "La stanza e piccola ma luminosa." },
  "il contratto": { example: "Il contratto inizia a maggio." },
  "le spese": {
    en: "the extra monthly costs",
    example: "Le spese mensili sono incluse nell'affitto?",
  },
  "il deposito": {
    it: "il deposito cauzionale",
    en: "the security deposit",
    example: "Il deposito cauzionale corrisponde a due mensilità.",
  },
  "la data di ingresso": {
    it: "la data di disponibilità",
    en: "the move-in date",
    example: "Qual è la data di disponibilità dell'appartamento?",
  },
  "il proprietario": { example: "Il proprietario vive in citta." },
  "incluso": { example: "Il wifi e incluso nel prezzo?" },
  "il trasloco": { example: "Il trasloco e previsto per lunedi." },
  "l'agenzia": { example: "L'agenzia chiede una commissione." },
  "l'annuncio": { example: "Ho visto il suo annuncio online." },
  "il problema": { example: "C'e un problema con il contratto?" },
  "la soluzione": { example: "Cerchiamo una soluzione semplice." },
  "l'obiettivo": { example: "Il mio obiettivo e entrare entro fine mese." },
  "il dettaglio": { example: "Mi manda un dettaglio in piu sulle spese?" },
  "la conferma": {
    en: "the confirmation",
    example: "Aspetto la conferma della visita per email.",
  },
  "la decisione": { example: "Le faccio sapere la mia decisione domani." },
  "il soggiorno": { example: "Il soggiorno e gia arredato." },
};

export const SEED_CARD_PATCHES: Array<{ matchIt: string; changes: Partial<LibraryCard> }> = [
  { matchIt: "ciao", changes: { en: "hello", example: "Ciao, come stai?" } },
  { matchIt: "mi chiamo...", changes: { it: "mi chiamo", en: "my name is", example: "Mi chiamo Luca." } },
  {
    matchIt: "sono allergico/a a...",
    changes: { it: "sono allergico a", en: "I am allergic to", example: "Sono allergico alle noccioline." },
  },
  {
    matchIt: "il primo / il secondo",
    changes: { it: "il primo piatto", en: "the first course", example: "Come primo piatto prendo la pasta." },
  },
  {
    matchIt: "avere fame / sete",
    changes: { it: "avere fame", en: "to be hungry", example: "Ho fame, andiamo a mangiare?" },
  },
  {
    matchIt: "il/la partner",
    changes: { it: "il partner", en: "the partner", example: "Il mio partner lavora a Milano." },
  },
  {
    matchIt: "assaggiare",
    changes: { en: "to taste", example: "Vuoi assaggiare il mio tiramisu?" },
  },
  {
    matchIt: "magari",
    changes: { en: "if only", example: "Magari fossi gia in vacanza." },
  },
  {
    matchIt: "piuttosto",
    changes: { en: "rather", example: "Preferisco restare a casa, piuttosto." },
  },
  {
    matchIt: "figurati",
    changes: { en: "don't mention it", example: "Grazie per l'aiuto. Figurati." },
  },
  {
    matchIt: "il portafoglio",
    changes: { en: "the wallet", example: "Ho lasciato il portafoglio sul tavolo." },
  },
  {
    matchIt: "la pratica",
    changes: { en: "the application file", example: "La pratica per il permesso e ancora in lavorazione." },
  },
  {
    matchIt: "il documento",
    changes: { en: "the document", example: "Mi manca ancora un documento per la domanda." },
  },
  {
    matchIt: "sbattere",
    changes: { en: "to slam", example: "Non sbattere la porta, per favore." },
  },
];

export const SEED_CARD_INSERTS: LibraryCard[] = [
  { it: "avere sete", en: "to be thirsty", example: "Dopo il viaggio ho molta sete.", tag: "food", level: "A2" },
  { it: "il secondo piatto", en: "the second course", example: "Come secondo piatto prendo il pesce.", tag: "food", level: "A2" },
  { it: "il cameriere", en: "waiter", example: "Il cameriere ci porta il menu.", tag: "food", level: "A2" },
  { it: "lavorare", en: "to work", example: "Lavoro in ufficio dal lunedi al venerdi.", tag: "work", level: "A2" },
  { it: "l'ufficio", en: "office", example: "Il mio ufficio e in centro.", tag: "work", level: "A2" },
  { it: "la partner", en: "the partner", example: "La mia partner arriva piu tardi.", tag: "social", level: "B1" },
  { it: "preferisco di no", en: "I would prefer not to", example: "Usciamo stasera? Preferisco di no, sono stanco.", tag: "social", level: "B1" },
  { it: "piuttosto che", en: "rather than", example: "Prendo il treno piuttosto che la macchina.", tag: "planning", level: "B1" },
  { it: "la pratica", en: "the paperwork file", example: "La pratica richiede ancora due firme.", tag: "bureaucracy", level: "B1" },
];

export const A1_AUDIT_EXPANSION: LibraryCard[] = [
  { it: "cerco una stanza singola", en: "I am looking for a single room", example: "Cerco una stanza singola vicino alla metro.", tag: "home", level: "A1" },
  { it: "l'affitto e trattabile", en: "the rent is negotiable", example: "L'affitto e trattabile o e fisso?", tag: "home", level: "A1" },
  { it: "quanto costa al mese", en: "how much is it per month", example: "Quanto costa al mese questa stanza?", tag: "home", level: "A1" },
  { it: "la stanza e arredata", en: "the room is furnished", example: "La stanza e arredata oppure no?", tag: "home", level: "A1" },
  { it: "e una stanza doppia", en: "it is a double room", example: "No, non e singola: e una stanza doppia.", tag: "home", level: "A1" },
  { it: "cerco un monolocale", en: "I am looking for a studio apartment", example: "Cerco un monolocale non troppo lontano dal centro.", tag: "home", level: "A1" },
  { it: "la cucina e condivisa", en: "the kitchen is shared", example: "La cucina e condivisa con altri due studenti.", tag: "home", level: "A1" },
  { it: "il bagno e privato", en: "the bathroom is private", example: "Il bagno e privato oppure condiviso?", tag: "home", level: "A1" },
  { it: "la stanza e libera da subito", en: "the room is available immediately", example: "La stanza e libera da subito.", tag: "home", level: "A1" },
  { it: "vorrei vedere l'appartamento", en: "I would like to see the apartment", example: "Vorrei vedere l'appartamento domani.", tag: "home", level: "A1" },
  { it: "a che piano si trova", en: "what floor is it on", example: "A che piano si trova l'appartamento?", tag: "home", level: "A1" },
  { it: "c'e l'ascensore", en: "is there a lift", example: "C'e l'ascensore nel palazzo?", tag: "home", level: "A1" },
  { it: "quanto dura il contratto", en: "how long is the contract", example: "Quanto dura il contratto di affitto?", tag: "home", level: "A1" },
  { it: "posso prendere le misure", en: "can I take the measurements", example: "Posso prendere le misure della stanza?", tag: "home", level: "A1" },
  { it: "quando posso entrare", en: "when can I move in", example: "Quando posso entrare nell'appartamento?", tag: "home", level: "A1" },
  { it: "la zona e tranquilla", en: "the area is quiet", example: "La zona e tranquilla la sera.", tag: "home", level: "A1" },
  { it: "e vicino alla metro", en: "it is near the metro", example: "Si, e vicino alla metro.", tag: "home", level: "A1" },
  { it: "mi serve un posto letto", en: "I need a bed space", example: "Per ora mi serve solo un posto letto.", tag: "home", level: "A1" },
  { it: "posso lasciare una caparra", en: "can I leave a deposit", example: "Posso lasciare una caparra oggi?", tag: "home", level: "A1" },
  { it: "la stanza da sulla strada", en: "the room faces the street", example: "La stanza da sulla strada principale.", tag: "home", level: "A1" },

  { it: "avete un tavolo libero", en: "do you have a free table", example: "Buonasera, avete un tavolo libero?", tag: "food", level: "A1" },
  { it: "abbiamo una prenotazione", en: "we have a reservation", example: "Abbiamo una prenotazione per le otto.", tag: "food", level: "A1" },
  { it: "preferisco stare dentro", en: "I prefer to sit inside", example: "Stasera preferisco stare dentro.", tag: "food", level: "A1" },
  { it: "vorrei ordinare", en: "I would like to order", example: "Vorrei ordinare adesso, grazie.", tag: "food", level: "A1" },
  { it: "per me la pasta", en: "for me, the pasta", example: "Per me la pasta al pomodoro.", tag: "food", level: "A1" },
  { it: "senza formaggio", en: "without cheese", example: "Per me la pasta senza formaggio.", tag: "food", level: "A1" },
  { it: "che cosa consiglia", en: "what do you recommend", example: "Che cosa consiglia oggi?", tag: "food", level: "A1" },
  { it: "e troppo salato", en: "it is too salty", example: "Mi dispiace, per me e troppo salato.", tag: "food", level: "A1" },
  { it: "potrebbe portarci del pane", en: "could you bring us some bread", example: "Potrebbe portarci del pane, per favore?", tag: "food", level: "A1" },
  { it: "dividiamo un antipasto", en: "we are sharing an appetizer", example: "Dividiamo un antipasto e poi prendiamo due primi.", tag: "food", level: "A1" },
  { it: "offro io", en: "it is on me", example: "Stasera offro io.", tag: "social", level: "A1" },
  { it: "che buona idea", en: "what a good idea", example: "Un aperitivo prima di cena? Che buona idea.", tag: "social", level: "A1" },
  { it: "arrivo tra dieci minuti", en: "I am arriving in ten minutes", example: "Scusa il ritardo, arrivo tra dieci minuti.", tag: "social", level: "A1" },
  { it: "ti aspetto fuori", en: "I will wait for you outside", example: "Ti aspetto fuori dal ristorante.", tag: "social", level: "A1" },
  { it: "grazie per l'invito", en: "thanks for the invitation", example: "Grazie per l'invito a cena.", tag: "social", level: "A1" },
  { it: "complimenti, e buonissimo", en: "compliments, it is delicious", example: "Complimenti, e buonissimo questo risotto.", tag: "social", level: "A1" },

  { it: "a che ora parte", en: "what time does it leave", example: "A che ora parte il prossimo treno?", tag: "travel", level: "A1" },
  { it: "da quale binario", en: "from which platform", example: "Da quale binario parte il regionale?", tag: "travel", level: "A1" },
  { it: "ho perso il treno", en: "I missed the train", example: "Scusi, ho perso il treno per Bologna.", tag: "travel", level: "A1" },
  { it: "il treno e cancellato", en: "the train is cancelled", example: "Il treno delle nove e cancellato.", tag: "travel", level: "A1" },
  { it: "devo cambiare a Firenze", en: "I have to change in Florence", example: "Devo cambiare a Firenze o vado diretto?", tag: "travel", level: "A1" },
  { it: "c'e un treno piu tardi", en: "is there a later train", example: "C'e un treno piu tardi per Roma?", tag: "travel", level: "A1" },
  { it: "vorrei cambiare il biglietto", en: "I would like to change the ticket", example: "Vorrei cambiare il biglietto per domani.", tag: "travel", level: "A1" },
  { it: "devo timbrare il biglietto", en: "do I need to validate the ticket", example: "Scusi, devo timbrare il biglietto?", tag: "travel", level: "A1" },
  { it: "c'e uno sciopero oggi", en: "there is a strike today", example: "Mi hanno detto che c'e uno sciopero oggi.", tag: "travel", level: "A1" },
  { it: "questa e la fermata giusta", en: "this is the right stop", example: "Scusi, questa e la fermata giusta?", tag: "travel", level: "A1" },
  { it: "devo prendere il regionale", en: "I need to take the regional train", example: "Per Pisa devo prendere il regionale?", tag: "travel", level: "A1" },
  { it: "quanto tempo ci vuole", en: "how long does it take", example: "Quanto tempo ci vuole fino a Milano?", tag: "travel", level: "A1" },
  { it: "il posto e occupato", en: "the seat is taken", example: "Mi scusi, questo posto e occupato?", tag: "travel", level: "A1" },
  { it: "il controllore arriva", en: "the ticket inspector is coming", example: "Prepara il biglietto, il controllore arriva.", tag: "travel", level: "A1" },
  { it: "scendo alla prossima", en: "I am getting off at the next stop", example: "No grazie, scendo alla prossima.", tag: "travel", level: "A1" },
  { it: "mi puo indicare l'uscita", en: "can you show me the exit", example: "Mi puo indicare l'uscita per i taxi?", tag: "travel", level: "A1" },

  { it: "mi fa male la gola", en: "my throat hurts", example: "Da ieri mi fa male la gola.", tag: "health", level: "A1" },
  { it: "ho la tosse", en: "I have a cough", example: "Buonasera, ho la tosse da due giorni.", tag: "health", level: "A1" },
  { it: "ho mal di stomaco", en: "I have a stomach ache", example: "Dopo pranzo ho mal di stomaco.", tag: "health", level: "A1" },
  { it: "da quanto tempo", en: "for how long", example: "Da quanto tempo hai la febbre?", tag: "health", level: "A1" },
  { it: "ha qualcosa per la febbre", en: "do you have something for a fever", example: "Ha qualcosa per la febbre?", tag: "health", level: "A1" },
  { it: "devo prendere una compressa", en: "I need to take one tablet", example: "Devo prendere una compressa dopo cena?", tag: "health", level: "A1" },
  { it: "prima o dopo i pasti", en: "before or after meals", example: "Questa medicina si prende prima o dopo i pasti?", tag: "health", level: "A1" },
  { it: "sono intollerante al lattosio", en: "I am lactose intolerant", example: "Sono intollerante al lattosio.", tag: "health", level: "A1" },
  { it: "mi gira la testa", en: "I feel dizzy", example: "Da stamattina mi gira la testa.", tag: "health", level: "A1" },
  { it: "devo riposare", en: "I need to rest", example: "Oggi devo riposare tutto il giorno.", tag: "health", level: "A1" },
  { it: "ha bisogno della ricetta", en: "do you need a prescription", example: "Per questo farmaco ha bisogno della ricetta?", tag: "health", level: "A1" },
  { it: "quante volte al giorno", en: "how many times a day", example: "Quante volte al giorno devo prenderlo?", tag: "health", level: "A1" },
  { it: "non mi sento bene", en: "I do not feel well", example: "Oggi non mi sento bene.", tag: "health", level: "A1" },
  { it: "mi serve una farmacia di turno", en: "I need a pharmacy on duty", example: "Mi serve una farmacia di turno qui vicino.", tag: "health", level: "A1" },

  { it: "sono in ritardo di cinque minuti", en: "I am five minutes late", example: "Scusa, sono in ritardo di cinque minuti.", tag: "time", level: "A1" },
  { it: "ci vediamo verso le sette", en: "let's meet around seven", example: "Ci vediamo verso le sette davanti al bar.", tag: "time", level: "A1" },
  { it: "sono libero domani mattina", en: "I am free tomorrow morning", example: "Sono libero domani mattina dalle nove.", tag: "time", level: "A1" },
  { it: "oggi non posso", en: "I cannot today", example: "Oggi non posso, ho gia un impegno.", tag: "time", level: "A1" },
  { it: "rimandiamo a domani", en: "let's postpone it until tomorrow", example: "Sei stanco? Rimandiamo a domani.", tag: "time", level: "A1" },
  { it: "lavoro fino alle sei", en: "I work until six", example: "Oggi lavoro fino alle sei.", tag: "time", level: "A1" },
  { it: "faccio pausa alle due", en: "I take a break at two", example: "Di solito faccio pausa alle due.", tag: "time", level: "A1" },
  { it: "di solito esco presto", en: "I usually leave early", example: "Il venerdi di solito esco presto.", tag: "time", level: "A1" },
  { it: "ho un appuntamento alle tre", en: "I have an appointment at three", example: "Domani ho un appuntamento alle tre.", tag: "time", level: "A1" },
  { it: "torno a casa tardi", en: "I get home late", example: "Il martedi torno a casa tardi.", tag: "time", level: "A1" },
  { it: "mi sveglio alle sette", en: "I wake up at seven", example: "Nei giorni feriali mi sveglio alle sette.", tag: "routine", level: "A1" },
  { it: "faccio la doccia la mattina", en: "I shower in the morning", example: "Di solito faccio la doccia la mattina.", tag: "routine", level: "A1" },

  { it: "come si dice in italiano", en: "how do you say it in Italian", example: "Scusi, come si dice in italiano?", tag: "basics", level: "A1" },
  { it: "come si scrive", en: "how do you spell it", example: "Come si scrive il suo cognome?", tag: "basics", level: "A1" },
  { it: "puo parlare piu piano", en: "can you speak more slowly", example: "Mi scusi, puo parlare piu piano?", tag: "basics", level: "A1" },
  { it: "non ho capito bene", en: "I did not understand well", example: "Mi dispiace, non ho capito bene.", tag: "basics", level: "A1" },
  { it: "puo scriverlo", en: "can you write it down", example: "Puo scriverlo su un foglio?", tag: "basics", level: "A1" },
  { it: "puo mostrarmelo", en: "can you show it to me", example: "Non capisco: puo mostrarmelo?", tag: "basics", level: "A1" },
  { it: "un attimo, per favore", en: "one moment, please", example: "Un attimo, per favore, cerco il portafoglio.", tag: "basics", level: "A1" },
  { it: "va bene cosi", en: "that is fine like that", example: "Si, va bene cosi, grazie.", tag: "basics", level: "A1" },
  { it: "non ne sono sicuro", en: "I am not sure", example: "Non ne sono sicuro, controllo subito.", tag: "basics", level: "A1" },
  { it: "puo aspettare un momento", en: "can you wait a moment", example: "Puo aspettare un momento, per favore?", tag: "basics", level: "A1" },
  { it: "ho bisogno di piu tempo", en: "I need more time", example: "Ho bisogno di piu tempo per decidere.", tag: "basics", level: "A1" },
  { it: "puo ripetere l'ultima frase", en: "can you repeat the last sentence", example: "Puo ripetere l'ultima frase, per favore?", tag: "basics", level: "A1" },
  { it: "sto ancora imparando", en: "I am still learning", example: "Parli pure piano, sto ancora imparando.", tag: "basics", level: "A1" },
  { it: "mi puo aiutare", en: "can you help me", example: "Mi puo aiutare con il modulo?", tag: "basics", level: "A1" },
];

// Sized to add roughly +154 A2 live rows and +204 B1 live rows via bidirectional inserts.
export const A2_AUDIT_EXPANSION: LibraryCard[] = [
  { it: "sono di Roma", en: "I am from Rome", example: "Ciao, sono di Roma.", tag: "basics", level: "A2" },
  { it: "piacere di conoscerti", en: "nice to meet you", example: "Piacere di conoscerti, io sono Anna.", tag: "basics", level: "A2" },
  { it: "di dove sei?", en: "where are you from?", example: "Di dove sei? Sono di Roma.", tag: "basics", level: "A2" },
  { it: "abito a", en: "I live in", example: "Abito a Milano.", tag: "basics", level: "A2" },
  { it: "ho ... anni", en: "I am ... years old", example: "Ho venticinque anni.", tag: "basics", level: "A2" },
  { it: "vengo da", en: "I come from", example: "Vengo da Londra.", tag: "basics", level: "A2" },
  { it: "come stai?", en: "how are you?", example: "Ciao, come stai?", tag: "basics", level: "A2" },
  { it: "bene, grazie", en: "fine, thanks", example: "Sto bene, grazie.", tag: "basics", level: "A2" },
  { it: "e tu?", en: "and you?", example: "Io sto bene, e tu?", tag: "basics", level: "A2" },
  { it: "la madre", en: "mother", example: "Mia madre si chiama Maria.", tag: "social", level: "A2" },
  { it: "il padre", en: "father", example: "Mio padre lavora in banca.", tag: "social", level: "A2" },
  { it: "il fratello", en: "brother", example: "Ho un fratello maggiore.", tag: "social", level: "A2" },
  { it: "la sorella", en: "sister", example: "Mia sorella ha vent'anni.", tag: "social", level: "A2" },
  { it: "i nonni", en: "grandparents", example: "I miei nonni vivono in campagna.", tag: "social", level: "A2" },
  { it: "lo zio", en: "uncle", example: "Mio zio abita a Napoli.", tag: "social", level: "A2" },
  { it: "la zia", en: "aunt", example: "La zia prepara la torta.", tag: "social", level: "A2" },
  { it: "il cugino", en: "cousin (m)", example: "Il mio cugino è simpatico.", tag: "social", level: "A2" },
  { it: "maggiore", en: "older", example: "Sono il fratello maggiore.", tag: "social", level: "A2" },
  { it: "minore", en: "younger", example: "La sorella minore è a scuola.", tag: "social", level: "A2" },
  { it: "quanti anni hai?", en: "how old are you?", example: "Quanti anni hai?", tag: "time", level: "A2" },
  { it: "ho vent'anni", en: "I am twenty years old", example: "Io ho vent'anni.", tag: "time", level: "A2" },
  { it: "ha trent'anni", en: "he/she is thirty years old", example: "Mio fratello ha trent'anni.", tag: "time", level: "A2" },
  { it: "ha quarant'anni", en: "he/she is forty years old", example: "Mia madre ha quarant'anni.", tag: "time", level: "A2" },
  { it: "quasi cento", en: "almost one hundred", example: "Mio nonno ha quasi cento anni.", tag: "time", level: "A2" },
  { it: "il numero di telefono", en: "the phone number", example: "Qual è il tuo numero di telefono?", tag: "time", level: "A2" },
  { it: "il compleanno", en: "birthday", example: "Il mio compleanno è in maggio.", tag: "time", level: "A2" },
  { it: "primo", en: "first", example: "È il mio primo giorno.", tag: "time", level: "A2" },
  { it: "secondo", en: "second", example: "Abito al secondo piano.", tag: "time", level: "A2" },
  { it: "in rosso", en: "in red", example: "Avete questa giacca anche in rosso?", tag: "shopping", level: "A2" },
  { it: "in blu", en: "in blue", example: "La preferisco in blu scuro.", tag: "shopping", level: "A2" },
  { it: "in verde", en: "in green", example: "Ce l'avete anche in verde?", tag: "shopping", level: "A2" },
  { it: "troppo grande", en: "too big", example: "Questa maglietta è troppo grande per me.", tag: "shopping", level: "A2" },
  { it: "troppo piccolo", en: "too small", example: "Questo camerino è troppo piccolo.", tag: "shopping", level: "A2" },
  { it: "molto bello", en: "very beautiful / very nice", example: "Questo vestito è molto bello.", tag: "shopping", level: "A2" },
  { it: "non mi piace molto", en: "I do not like it much", example: "Questo colore non mi piace molto.", tag: "shopping", level: "A2" },
  { it: "come nuovo", en: "like new", example: "Il tavolo è quasi come nuovo.", tag: "shopping", level: "A2" },
  { it: "un po' vecchio", en: "a bit old", example: "Il divano è un po' vecchio.", tag: "shopping", level: "A2" },
  { it: "verde chiaro", en: "light green", example: "Preferisco il verde chiaro.", tag: "shopping", level: "A2" },
  { it: "la pizza", en: "pizza", example: "Vorrei una pizza margherita.", tag: "food", level: "A2" },
  { it: "la pasta", en: "pasta", example: "La pasta è al dente.", tag: "food", level: "A2" },
  { it: "il caffè", en: "coffee", example: "Prendo un caffè, grazie.", tag: "food", level: "A2" },
  { it: "l'acqua", en: "water", example: "Un'acqua naturale, per favore.", tag: "food", level: "A2" },
  { it: "il vino", en: "wine", example: "Un bicchiere di vino rosso.", tag: "food", level: "A2" },
  { it: "il pane", en: "bread", example: "Vorrei del pane fresco.", tag: "food", level: "A2" },
  { it: "il formaggio", en: "cheese", example: "Il parmigiano è delizioso.", tag: "food", level: "A2" },
  { it: "la carne", en: "meat", example: "Non mangio la carne.", tag: "food", level: "A2" },
  { it: "la verdura", en: "vegetables", example: "Mangio molta verdura.", tag: "food", level: "A2" },
  { it: "il dolce", en: "dessert", example: "Come dolce prendo il tiramisù.", tag: "food", level: "A2" },
  { it: "la cucina", en: "kitchen", example: "La cucina è grande.", tag: "home", level: "A2" },
  { it: "il bagno", en: "bathroom", example: "Il bagno è al primo piano.", tag: "home", level: "A2" },
  { it: "la camera da letto", en: "bedroom", example: "La camera da letto è luminosa.", tag: "home", level: "A2" },
  { it: "il salotto", en: "living room", example: "Guardiamo la TV in salotto.", tag: "home", level: "A2" },
  { it: "il balcone", en: "balcony", example: "C'è un balcone con vista sul mare.", tag: "home", level: "A2" },
  { it: "il tavolo", en: "table", example: "Il tavolo è in cucina.", tag: "home", level: "A2" },
  { it: "la sedia", en: "chair", example: "Ci sono quattro sedie.", tag: "home", level: "A2" },
  { it: "il divano", en: "sofa", example: "Mi siedo sul divano.", tag: "home", level: "A2" },
  { it: "la finestra", en: "window", example: "Apri la finestra, per favore.", tag: "home", level: "A2" },
  { it: "la maglietta", en: "t-shirt", example: "Questa maglietta è troppo grande.", tag: "shopping", level: "A2" },
  { it: "i pantaloni", en: "trousers", example: "Quei pantaloni costano troppo.", tag: "shopping", level: "A2" },
  { it: "le scarpe", en: "shoes", example: "Mi piacciono quelle scarpe.", tag: "shopping", level: "A2" },
  { it: "la giacca", en: "jacket", example: "Ho bisogno di una giacca nuova.", tag: "shopping", level: "A2" },
  { it: "il vestito", en: "dress/suit", example: "Che bel vestito!", tag: "shopping", level: "A2" },
  { it: "stretto", en: "tight", example: "Questi pantaloni sono stretti.", tag: "shopping", level: "A2" },
  { it: "largo", en: "loose/wide", example: "La giacca è troppo larga.", tag: "shopping", level: "A2" },
  { it: "lunedì", en: "Monday", example: "Il lunedì vado in palestra.", tag: "time", level: "A2" },
  { it: "venerdì", en: "Friday", example: "Venerdì sera usciamo.", tag: "time", level: "A2" },
  { it: "il fine settimana", en: "weekend", example: "Cosa fai il fine settimana?", tag: "time", level: "A2" },
  { it: "gennaio", en: "January", example: "In gennaio fa freddo.", tag: "time", level: "A2" },
  { it: "agosto", en: "August", example: "In agosto andiamo al mare.", tag: "time", level: "A2" },
  { it: "la settimana", en: "week", example: "La prossima settimana ho un esame.", tag: "time", level: "A2" },
  { it: "il mese", en: "month", example: "Questo mese è corto.", tag: "time", level: "A2" },
  { it: "ieri", en: "yesterday", example: "Ieri ho lavorato tutto il giorno.", tag: "time", level: "A2" },
  { it: "il medico", en: "doctor", example: "Faccio il medico.", tag: "work", level: "A2" },
  { it: "l'insegnante", en: "teacher", example: "Mia madre fa l'insegnante.", tag: "work", level: "A2" },
  { it: "l'avvocato", en: "lawyer", example: "Mio zio è avvocato.", tag: "work", level: "A2" },
  { it: "l'ingegnere", en: "engineer", example: "Lavoro come ingegnere.", tag: "work", level: "A2" },
  { it: "il cuoco", en: "cook/chef", example: "Il cuoco è molto bravo.", tag: "work", level: "A2" },
];

export const B1_AUDIT_EXPANSION: LibraryCard[] = [
  { it: "ho mangiato una pizza", en: "I ate a pizza", example: "Ieri sera ho mangiato una pizza.", tag: "routine", level: "B1" },
  { it: "sono andato al cinema", en: "I went to the cinema", example: "Sabato sono andato al cinema con Marta.", tag: "routine", level: "B1" },
  { it: "ho visto un bel film", en: "I saw a nice film", example: "Ho visto un bel film ieri sera.", tag: "routine", level: "B1" },
  { it: "sono partito stamattina", en: "I left this morning", example: "Sono partito stamattina molto presto.", tag: "routine", level: "B1" },
  { it: "ho comprato un regalo", en: "I bought a gift", example: "Ho comprato un regalo per mia sorella.", tag: "routine", level: "B1" },
  { it: "sono tornato a casa tardi", en: "I came home late", example: "Dopo la cena sono tornato a casa tardi.", tag: "routine", level: "B1" },
  { it: "ho scritto un'email", en: "I wrote an email", example: "Ho scritto un'email al professore.", tag: "routine", level: "B1" },
  { it: "sono rimasto a casa", en: "I stayed at home", example: "Domenica sono rimasto a casa tutto il giorno.", tag: "routine", level: "B1" },
  { it: "ho fatto i compiti", en: "I did my homework", example: "Prima di uscire ho fatto i compiti.", tag: "routine", level: "B1" },
  { it: "sono uscito con gli amici", en: "I went out with friends", example: "Venerdì sono uscito con gli amici.", tag: "routine", level: "B1" },
  { it: "da bambino giocavo fuori", en: "as a child I used to play outside", example: "Da bambino giocavo fuori con i miei amici.", tag: "social", level: "B1" },
  { it: "andavo al mare ogni estate", en: "I used to go to the seaside every summer", example: "Quando vivevo a Roma, andavo al mare ogni estate.", tag: "social", level: "B1" },
  { it: "era una giornata bellissima", en: "it was a beautiful day", example: "Era una giornata bellissima e non faceva freddo.", tag: "social", level: "B1" },
  { it: "faceva caldo quel giorno", en: "it was hot that day", example: "Faceva caldo quel giorno, quindi siamo rimasti in spiaggia.", tag: "social", level: "B1" },
  { it: "c'era un bel sole", en: "there was lovely sunshine", example: "C'era un bel sole e il parco era pieno di gente.", tag: "social", level: "B1" },
  { it: "mentre stavo mangiando", en: "while I was eating", example: "Mentre stavo mangiando, è squillato il telefono.", tag: "social", level: "B1" },
  { it: "studiavo sempre la sera", en: "I always used to study in the evening", example: "Quando lavoravo di giorno, studiavo sempre la sera.", tag: "social", level: "B1" },
  { it: "ogni domenica pranzavamo dai nonni", en: "every Sunday we used to have lunch at our grandparents'", example: "Da piccoli, ogni domenica pranzavamo dai nonni.", tag: "social", level: "B1" },
  { it: "vivevo a Firenze", en: "I used to live in Florence", example: "Prima dell'università vivevo a Firenze con la mia famiglia.", tag: "social", level: "B1" },
  { it: "sembrava un sogno", en: "it seemed like a dream", example: "Con quel panorama sembrava un sogno.", tag: "social", level: "B1" },
  { it: "improvvisamente ha iniziato a piovere", en: "suddenly it started raining", example: "Eravamo al parco e improvvisamente ha iniziato a piovere.", tag: "social", level: "B1" },
  { it: "nel frattempo aspettavo fuori", en: "meanwhile I was waiting outside", example: "Tu parlavi con il dottore e nel frattempo aspettavo fuori.", tag: "social", level: "B1" },
  { it: "a un certo punto è arrivata la polizia", en: "at a certain point the police arrived", example: "La festa era rumorosa e a un certo punto è arrivata la polizia.", tag: "social", level: "B1" },
  { it: "avevo già finito", en: "I had already finished", example: "Quando mi hai chiamato, avevo già finito il lavoro.", tag: "social", level: "B1" },
  { it: "stavo per uscire", en: "I was about to go out", example: "Stavo per uscire quando hai bussato alla porta.", tag: "social", level: "B1" },
  { it: "all'improvviso si è spenta la luce", en: "all of a sudden the light went out", example: "Stavamo cenando e all'improvviso si è spenta la luce.", tag: "social", level: "B1" },
  { it: "di solito prendevo il treno", en: "I usually used to take the train", example: "Quando lavoravo a Milano, di solito prendevo il treno.", tag: "social", level: "B1" },
  { it: "quella volta sono andato in macchina", en: "that time I went by car", example: "Di solito andavo in treno, ma quella volta sono andato in macchina.", tag: "social", level: "B1" },
  { it: "cosa è successo?", en: "what happened?", example: "Ti vedo agitato: cosa è successo?", tag: "social", level: "B1" },
  { it: "ti racconto cosa è successo", en: "I'll tell you what happened", example: "Siediti un attimo e ti racconto cosa è successo.", tag: "social", level: "B1" },
  { it: "andrò al mare", en: "I will go to the seaside", example: "Se fa bel tempo, andrò al mare.", tag: "planning", level: "B1" },
  { it: "farò una torta", en: "I will make a cake", example: "Per la festa farò una torta al cioccolato.", tag: "planning", level: "B1" },
  { it: "sarà una bella giornata", en: "it will be a nice day", example: "Domani sarà una bella giornata.", tag: "planning", level: "B1" },
  { it: "avrò più tempo", en: "I will have more time", example: "Il mese prossimo avrò più tempo libero.", tag: "planning", level: "B1" },
  { it: "verrò alla tua festa", en: "I will come to your party", example: "Se finisco presto, verrò alla tua festa.", tag: "planning", level: "B1" },
  { it: "potrò aiutarti", en: "I will be able to help you", example: "Domani pomeriggio potrò aiutarti.", tag: "planning", level: "B1" },
  { it: "dovrò studiare di più", en: "I will have to study more", example: "Per l'esame dovrò studiare di più.", tag: "planning", level: "B1" },
  { it: "tra due settimane", en: "in two weeks", example: "Tra due settimane parto per le vacanze.", tag: "planning", level: "B1" },
  { it: "l'anno prossimo", en: "next year", example: "L'anno prossimo viaggerò di più.", tag: "planning", level: "B1" },
  { it: "chissà cosa succederà", en: "who knows what will happen", example: "Chissà cosa succederà domani.", tag: "planning", level: "B1" },
  { it: "il volo", en: "flight", example: "Il volo parte alle dieci.", tag: "travel", level: "B1" },
  { it: "la valigia", en: "suitcase", example: "Devo fare la valigia.", tag: "travel", level: "B1" },
  { it: "l'albergo", en: "hotel", example: "Ho prenotato un albergo in centro.", tag: "travel", level: "B1" },
  { it: "la prenotazione", en: "reservation", example: "Ho una prenotazione a nome Rossi.", tag: "travel", level: "B1" },
  { it: "il passaporto", en: "passport", example: "Non dimenticare il passaporto!", tag: "travel", level: "B1" },
  { it: "la cartina", en: "map", example: "Hai una cartina della città?", tag: "travel", level: "B1" },
  { it: "il check-in", en: "check-in", example: "Il check-in è alle tre.", tag: "travel", level: "B1" },
  { it: "l'escursione", en: "excursion", example: "Facciamo un'escursione domani.", tag: "travel", level: "B1" },
  { it: "il souvenir", en: "souvenir", example: "Ho comprato dei souvenir.", tag: "travel", level: "B1" },
  { it: "all'estero", en: "abroad", example: "Quest'estate vado all'estero.", tag: "travel", level: "B1" },
  { it: "più caro", en: "more expensive", example: "Questo è più caro di quello.", tag: "shopping", level: "B1" },
  { it: "meno costoso", en: "less expensive", example: "La camicia è meno costosa.", tag: "shopping", level: "B1" },
  { it: "migliore", en: "better", example: "Questa qualità è migliore.", tag: "shopping", level: "B1" },
  { it: "peggiore", en: "worse", example: "Il servizio qui è peggiore.", tag: "shopping", level: "B1" },
  { it: "il più bello", en: "the most beautiful", example: "È il vestito più bello.", tag: "shopping", level: "B1" },
  { it: "conveniente", en: "affordable/good deal", example: "Questo negozio è conveniente.", tag: "shopping", level: "B1" },
  { it: "la qualità", en: "quality", example: "La qualità è ottima.", tag: "shopping", level: "B1" },
  { it: "il marchio", en: "brand", example: "Che marchio preferisci?", tag: "shopping", level: "B1" },
  { it: "il cambio", en: "exchange/return", example: "Posso fare il cambio?", tag: "shopping", level: "B1" },
  { it: "provarsi", en: "to try on (reflexive)", example: "Mi provo questa giacca.", tag: "shopping", level: "B1" },
  { it: "la riunione", en: "meeting", example: "Ho una riunione alle dieci.", tag: "work", level: "B1" },
  { it: "il capo", en: "boss", example: "Il capo vuole il report domani.", tag: "work", level: "B1" },
  { it: "il progetto", en: "project", example: "Stiamo lavorando a un nuovo progetto.", tag: "work", level: "B1" },
  { it: "il curriculum", en: "CV/resume", example: "Ho mandato il mio curriculum.", tag: "work", level: "B1" },
  { it: "il colloquio", en: "job interview", example: "Ho un colloquio domani.", tag: "work", level: "B1" },
  { it: "assumere", en: "to hire", example: "L'azienda vuole assumere dieci persone.", tag: "work", level: "B1" },
  { it: "licenziare", en: "to fire", example: "Hanno licenziato tre colleghi.", tag: "work", level: "B1" },
  { it: "lo straordinario", en: "overtime", example: "Faccio spesso lo straordinario.", tag: "work", level: "B1" },
  { it: "fare carriera", en: "to advance one's career", example: "Vuole fare carriera in finanza.", tag: "work", level: "B1" },
  { it: "il computer", en: "computer", example: "Il computer non funziona.", tag: "work", level: "B1" },
  { it: "lo smartphone", en: "smartphone", example: "Ho comprato uno smartphone nuovo.", tag: "work", level: "B1" },
  { it: "il sito web", en: "website", example: "Visita il nostro sito web.", tag: "work", level: "B1" },
  { it: "il programma", en: "software/program", example: "Quale programma usi?", tag: "work", level: "B1" },
  { it: "la password", en: "password", example: "Ho dimenticato la password.", tag: "work", level: "B1" },
  { it: "aggiornare", en: "to update", example: "Devi aggiornare il sistema.", tag: "work", level: "B1" },
  { it: "il Wi-Fi", en: "Wi-Fi", example: "Qual è la password del Wi-Fi?", tag: "work", level: "B1" },
  { it: "caricare", en: "to charge/upload", example: "Devo caricare il telefono.", tag: "work", level: "B1" },
  { it: "funzionare", en: "to work/function", example: "L'app non funziona bene.", tag: "work", level: "B1" },
  { it: "il ragazzo", en: "boyfriend", example: "Ti presento il mio ragazzo.", tag: "social", level: "B1" },
  { it: "la ragazza", en: "girlfriend", example: "La mia ragazza è di Napoli.", tag: "social", level: "B1" },
  { it: "fidanzarsi", en: "to get engaged", example: "Si sono fidanzati a Natale.", tag: "social", level: "B1" },
  { it: "sposarsi", en: "to get married", example: "Si sposano a giugno.", tag: "social", level: "B1" },
  { it: "fidarsi", en: "to trust", example: "Mi fido di te.", tag: "social", level: "B1" },
  { it: "volersi bene", en: "to love each other", example: "Ci vogliamo molto bene.", tag: "social", level: "B1" },
  { it: "lasciare", en: "to leave/break up", example: "L'ha lasciata il mese scorso.", tag: "social", level: "B1" },
  { it: "il matrimonio", en: "wedding/marriage", example: "Il matrimonio è a settembre.", tag: "social", level: "B1" },
  { it: "potrei aiutarti", en: "I could help you", example: "Potrei aiutarti domani pomeriggio.", tag: "planning", level: "B1" },
  { it: "dovrei studiare di più", en: "I should study more", example: "Per passare l'esame dovrei studiare di più.", tag: "planning", level: "B1" },
  { it: "farei diversamente", en: "I would do it differently", example: "Al posto tuo, farei diversamente.", tag: "planning", level: "B1" },
  { it: "andrei volentieri", en: "I would gladly go", example: "Andrei volentieri in Giappone.", tag: "planning", level: "B1" },
  { it: "sarebbe bello", en: "it would be nice", example: "Sarebbe bello vivere al mare.", tag: "planning", level: "B1" },
  { it: "al posto tuo", en: "in your place", example: "Al posto tuo, accetterei l'offerta.", tag: "planning", level: "B1" },
  { it: "volentieri", en: "gladly", example: "Verrei volentieri alla cena.", tag: "planning", level: "B1" },
  { it: "se potessi", en: "if I could", example: "Se potessi, vivrei in Italia.", tag: "planning", level: "B1" },
  { it: "lo conosco bene", en: "I know him well", example: "Marco? Lo conosco bene.", tag: "social", level: "B1" },
  { it: "li vedo ogni giorno", en: "I see them every day", example: "I miei colleghi? Li vedo ogni giorno.", tag: "social", level: "B1" },
  { it: "mi chiami stasera", en: "call me tonight", example: "Se hai tempo, mi chiami stasera?", tag: "social", level: "B1" },
  { it: "ti aspetto alle otto", en: "I am waiting for you at eight", example: "Ti aspetto alle otto davanti al cinema.", tag: "social", level: "B1" },
  { it: "ci invitano alla festa", en: "they are inviting us to the party", example: "Quest'anno ci invitano alla festa di Anna.", tag: "social", level: "B1" },
  { it: "conosci quella ragazza?", en: "do you know that girl?", example: "Conosci quella ragazza che lavora con Luca?", tag: "social", level: "B1" },
  { it: "ti chiamo domani", en: "I will call you tomorrow", example: "Adesso sono in riunione, ti chiamo domani.", tag: "social", level: "B1" },
  { it: "ti aspetto fuori", en: "I am waiting for you outside", example: "Fai con calma, ti aspetto fuori.", tag: "social", level: "B1" },
];

if (A2_AUDIT_EXPANSION.length !== 77) {
  throw new Error(`Expected 77 A2 audit expansion cards, got ${A2_AUDIT_EXPANSION.length}`);
}

if (B1_AUDIT_EXPANSION.length !== 102) {
  throw new Error(`Expected 102 B1 audit expansion cards, got ${B1_AUDIT_EXPANSION.length}`);
}
