import { mutation } from "./_generated/server";
import { v } from "convex/values";

// All vocab data inline to avoid importing from src/
const allVocab = [
  // ─── Sport & Champions
  { it: "il fuoriclasse", en: "the champion / outstanding person", example: "Messi è un fuoriclasse assoluto.", tag: "sport" },
  { it: "la determinazione", en: "determination", example: "Senza determinazione non si arriva da nessuna parte.", tag: "sport" },
  { it: "il talento naturale", en: "natural talent", example: "Il talento naturale non basta, serve anche lavoro.", tag: "sport" },
  { it: "la disciplina", en: "discipline", example: "La disciplina è la chiave del successo.", tag: "sport" },
  { it: "superare i propri limiti", en: "to exceed one's limits", example: "Ogni atleta deve superare i propri limiti.", tag: "sport" },
  { it: "la costanza", en: "consistency / perseverance", example: "La costanza fa la differenza nel lungo termine.", tag: "sport" },
  { it: "il sacrificio", en: "sacrifice", example: "Ci vogliono molti sacrifici per diventare campioni.", tag: "sport" },
  { it: "la mentalità vincente", en: "winning mentality", example: "Serve una mentalità vincente per competere.", tag: "sport" },
  { it: "allenarsi duramente", en: "to train hard", example: "Si allena duramente ogni giorno.", tag: "sport" },
  { it: "raggiungere un obiettivo", en: "to achieve a goal", example: "Ha raggiunto il suo obiettivo dopo anni di lavoro.", tag: "sport" },
  { it: "avere la stoffa", en: "to have what it takes", example: "Quel ragazzo ha la stoffa del campione.", tag: "sport" },
  { it: "fare il salto di qualità", en: "to level up", example: "Quest'anno ha fatto il salto di qualità.", tag: "sport" },
  // ─── Daily Routines
  { it: "svegliarsi presto", en: "to wake up early", example: "Mi sveglio presto ogni mattina.", tag: "routine" },
  { it: "fare colazione", en: "to have breakfast", example: "Faccio colazione alle sette.", tag: "routine" },
  { it: "la routine mattutina", en: "morning routine", example: "La mia routine mattutina è molto semplice.", tag: "routine" },
  { it: "andare in palestra", en: "to go to the gym", example: "Vado in palestra tre volte a settimana.", tag: "routine" },
  { it: "fare la spesa", en: "to do grocery shopping", example: "Faccio la spesa al supermercato.", tag: "routine" },
  { it: "rilassarsi la sera", en: "to relax in the evening", example: "Mi rilasso la sera guardando un film.", tag: "routine" },
  { it: "l'abitudine quotidiana", en: "daily habit", example: "Leggere è la mia abitudine quotidiana.", tag: "routine" },
  { it: "organizzare la giornata", en: "to organize the day", example: "Organizzo la giornata la mattina presto.", tag: "routine" },
  // ─── Fitness & Health
  { it: "l'allenamento", en: "training/workout", example: "L'allenamento di oggi è stato intenso.", tag: "fitness" },
  { it: "il recupero muscolare", en: "muscle recovery", example: "Il recupero muscolare è fondamentale.", tag: "fitness" },
  { it: "fare stretching", en: "to stretch", example: "Faccio stretching dopo ogni allenamento.", tag: "fitness" },
  { it: "la resistenza fisica", en: "physical endurance", example: "La resistenza fisica migliora con il tempo.", tag: "fitness" },
  { it: "mangiare sano", en: "to eat healthy", example: "Cerco di mangiare sano ogni giorno.", tag: "fitness" },
  { it: "il riposo attivo", en: "active rest", example: "Il riposo attivo aiuta il recupero.", tag: "fitness" },
  { it: "allenarsi regolarmente", en: "to train regularly", example: "Mi alleno regolarmente durante la settimana.", tag: "fitness" },
  { it: "il benessere fisico", en: "physical well-being", example: "Il benessere fisico è importante per la salute.", tag: "fitness" },
  // ─── Work & Productivity
  { it: "la scadenza", en: "the deadline", example: "La scadenza del progetto è domani.", tag: "work" },
  { it: "lavorare da remoto", en: "to work remotely", example: "Lavoro da remoto da due anni.", tag: "work" },
  { it: "gestire il tempo", en: "to manage time", example: "Bisogna imparare a gestire il tempo.", tag: "work" },
  { it: "essere produttivo", en: "to be productive", example: "Sono più produttivo la mattina.", tag: "work" },
  { it: "risolvere un problema", en: "to solve a problem", example: "Dobbiamo risolvere questo problema insieme.", tag: "work" },
  { it: "il flusso di lavoro", en: "the workflow", example: "Il flusso di lavoro è molto efficiente.", tag: "work" },
  { it: "prendere appunti", en: "to take notes", example: "Prendo appunti durante le riunioni.", tag: "work" },
  { it: "il progetto in corso", en: "ongoing project", example: "Il progetto in corso va molto bene.", tag: "work" },
  // ─── Connectors & Conversation
  { it: "comunque", en: "anyway / however", example: "Comunque, non è un problema.", tag: "connectors" },
  { it: "infatti", en: "in fact / indeed", example: "Infatti, hai ragione.", tag: "connectors" },
  { it: "piuttosto", en: "rather / quite", example: "È piuttosto difficile da spiegare.", tag: "connectors" },
  { it: "insomma", en: "in short / basically", example: "Insomma, non mi è piaciuto.", tag: "connectors" },
  { it: "anzi", en: "on the contrary / actually", example: "Non è facile, anzi è molto difficile.", tag: "connectors" },
  { it: "magari", en: "maybe / I wish", example: "Magari potremmo andare al cinema stasera.", tag: "connectors" },
  { it: "eppure", en: "and yet / still", example: "Ha studiato tanto, eppure non ha passato l'esame.", tag: "connectors" },
  { it: "siccome", en: "since / given that", example: "Siccome piove, restiamo a casa.", tag: "connectors" },
  { it: "nonostante", en: "despite / in spite of", example: "Nonostante la pioggia, siamo usciti.", tag: "connectors" },
  { it: "a proposito", en: "by the way", example: "A proposito, hai visto il nuovo film?", tag: "connectors" },
  // ─── Opinions & Feelings
  { it: "mi sembra che", en: "it seems to me that", example: "Mi sembra che tu abbia ragione.", tag: "opinions" },
  { it: "secondo me", en: "in my opinion", example: "Secondo me, è la scelta giusta.", tag: "opinions" },
  { it: "non ne sono sicuro", en: "I'm not sure about it", example: "Non ne sono sicuro, devo controllare.", tag: "opinions" },
  { it: "vale la pena", en: "it's worth it", example: "Vale la pena provare.", tag: "opinions" },
  { it: "non vedo l'ora", en: "I can't wait", example: "Non vedo l'ora di andare in vacanza.", tag: "opinions" },
  { it: "mi dà fastidio", en: "it bothers me", example: "Mi dà fastidio il rumore.", tag: "opinions" },
  { it: "sono d'accordo", en: "I agree", example: "Sono d'accordo con te.", tag: "opinions" },
  { it: "non è un granché", en: "it's nothing special", example: "Il ristorante non è un granché.", tag: "opinions" },
  { it: "avere voglia di", en: "to feel like (doing sth)", example: "Ho voglia di un gelato.", tag: "opinions" },
  { it: "mi fa piacere", en: "it pleases me / I'm glad", example: "Mi fa piacere sentirti.", tag: "opinions" },
  // ─── Food & Restaurant
  { it: "prenotare un tavolo", en: "to book a table", example: "Vorrei prenotare un tavolo per due.", tag: "food" },
  { it: "il conto", en: "the bill", example: "Scusi, il conto per favore.", tag: "food" },
  { it: "il piatto del giorno", en: "dish of the day", example: "Qual è il piatto del giorno?", tag: "food" },
  { it: "assaggiare", en: "to taste / to try", example: "Vuoi assaggiare il mio tiramisù?", tag: "food" },
  { it: "un bicchiere di vino", en: "a glass of wine", example: "Prendo un bicchiere di vino rosso.", tag: "food" },
  { it: "il primo / il secondo", en: "first / second course", example: "Come primo prendo la pasta e come secondo il pesce.", tag: "food" },
  { it: "avere fame / sete", en: "to be hungry / thirsty", example: "Ho fame, andiamo a mangiare?", tag: "food" },
  { it: "la ricetta", en: "the recipe", example: "Mi puoi dare la ricetta?", tag: "food" },
  // ─── Travel & City
  { it: "fare un giro", en: "to take a walk / tour", example: "Facciamo un giro per il centro.", tag: "travel" },
  { it: "perdersi", en: "to get lost", example: "Mi sono perso nelle stradine.", tag: "travel" },
  { it: "il quartiere", en: "the neighborhood", example: "Abito in un quartiere tranquillo.", tag: "travel" },
  { it: "prendere il treno", en: "to take the train", example: "Devo prendere il treno delle otto.", tag: "travel" },
  { it: "il biglietto di andata e ritorno", en: "round-trip ticket", example: "Un biglietto di andata e ritorno per Roma, per favore.", tag: "travel" },
  { it: "godersi il viaggio", en: "to enjoy the trip", example: "Bisogna godersi il viaggio.", tag: "travel" },
  { it: "la meta", en: "the destination", example: "Qual è la meta delle vacanze?", tag: "travel" },
  { it: "fare le valigie", en: "to pack the suitcases", example: "Devo ancora fare le valigie.", tag: "travel" },
  // ─── Verbs & Grammar Patterns
  { it: "stare per + infinito", en: "to be about to", example: "Sto per uscire.", tag: "grammar" },
  { it: "farcela", en: "to manage / to make it", example: "Ce la faccio, non ti preoccupare.", tag: "grammar" },
  { it: "andarsene", en: "to leave / to go away", example: "Me ne vado, è tardi.", tag: "grammar" },
  { it: "metterci", en: "to take (time)", example: "Ci metto mezz'ora per arrivare.", tag: "grammar" },
  { it: "volerci", en: "to take / to need (impersonal)", example: "Ci vogliono due ore per arrivare.", tag: "grammar" },
  { it: "cavarsela", en: "to manage / to get by", example: "Me la cavo bene con l'italiano.", tag: "grammar" },
  { it: "rendersene conto", en: "to realize", example: "Non me ne sono reso conto.", tag: "grammar" },
  { it: "averne abbastanza", en: "to have had enough", example: "Ne ho abbastanza di questo traffico.", tag: "grammar" },
  // ─── Idiomatic Expressions
  { it: "in bocca al lupo", en: "good luck (lit: in the wolf's mouth)", example: "Domani hai l'esame? In bocca al lupo!", tag: "idioms" },
  { it: "non c'entra niente", en: "it has nothing to do with it", example: "Questo non c'entra niente con il problema.", tag: "idioms" },
  { it: "avere un sacco di", en: "to have a lot of", example: "Ho un sacco di cose da fare.", tag: "idioms" },
  { it: "che figata!", en: "how cool! (informal)", example: "Hai comprato la moto? Che figata!", tag: "idioms" },
  { it: "dai!", en: "come on! / go on!", example: "Dai, non essere timido.", tag: "idioms" },
  { it: "boh", en: "I dunno / who knows", example: "Dove vuoi andare? Boh, non lo so.", tag: "idioms" },
  { it: "figurati", en: "don't mention it / imagine that", example: "Grazie! — Figurati, è stato un piacere.", tag: "idioms" },
  { it: "che palle!", en: "what a pain! (informal)", example: "Ancora pioggia? Che palle!", tag: "idioms" },
  { it: "fare bella figura", en: "to make a good impression", example: "In Italia è importante fare bella figura.", tag: "idioms" },
  { it: "tirare avanti", en: "to get by / to keep going", example: "Si tira avanti, giorno dopo giorno.", tag: "idioms" },
  // ─── Finance & Trading
  { it: "il rendimento", en: "the return / yield", example: "Il rendimento del portafoglio è stato buono.", tag: "finance" },
  { it: "il mercato azionario", en: "the stock market", example: "Il mercato azionario è volatile oggi.", tag: "finance" },
  { it: "investire", en: "to invest", example: "Preferisco investire a lungo termine.", tag: "finance" },
  { it: "il rischio", en: "risk", example: "Bisogna sempre calcolare il rischio.", tag: "finance" },
  { it: "il tasso di interesse", en: "interest rate", example: "La BCE ha alzato il tasso di interesse.", tag: "finance" },
  { it: "il portafoglio", en: "the portfolio / wallet", example: "Ho diversificato il portafoglio.", tag: "finance" },
  // ─── Tech & Digital
  { it: "l'intelligenza artificiale", en: "artificial intelligence", example: "L'intelligenza artificiale sta cambiando tutto.", tag: "tech" },
  { it: "il codice sorgente", en: "source code", example: "Ho scritto il codice sorgente in Python.", tag: "tech" },
  { it: "l'aggiornamento", en: "the update", example: "C'è un nuovo aggiornamento disponibile.", tag: "tech" },
  { it: "scaricare", en: "to download", example: "Devo scaricare l'applicazione.", tag: "tech" },
  // ─── Emotions & Relationships (extended)
  { it: "innamorarsi", en: "to fall in love", example: "Mi sono innamorato al primo sguardo.", tag: "emotions" },
  { it: "litigare", en: "to argue / to quarrel", example: "Non mi piace litigare per niente.", tag: "emotions" },
  { it: "fare pace", en: "to make up / to reconcile", example: "Dopo la discussione abbiamo fatto pace.", tag: "emotions" },
  { it: "essere geloso", en: "to be jealous", example: "Non essere geloso, è solo un amico.", tag: "emotions" },
  { it: "fidarsi di", en: "to trust (someone)", example: "Mi fido di te completamente.", tag: "emotions" },
  { it: "tradire", en: "to betray / to cheat on", example: "Non potrei mai tradire la fiducia di qualcuno.", tag: "emotions" },
  { it: "il/la partner", en: "the partner", example: "Il mio partner è molto comprensivo.", tag: "emotions" },
  { it: "la coppia", en: "the couple", example: "Sono una coppia molto affiatata.", tag: "emotions" },
  { it: "andare d'accordo", en: "to get along", example: "Andiamo d'accordo su tutto.", tag: "emotions" },
  { it: "il rapporto", en: "the relationship", example: "Il nostro rapporto è migliorato molto.", tag: "emotions" },
  { it: "sentirsi solo/a", en: "to feel lonely", example: "A volte mi sento solo la sera.", tag: "emotions" },
  { it: "preoccuparsi", en: "to worry", example: "Non preoccuparti, andrà tutto bene.", tag: "emotions" },
  { it: "vergognarsi", en: "to be ashamed / embarrassed", example: "Mi vergogno di quello che ho detto.", tag: "emotions" },
  { it: "arrabbiarsi", en: "to get angry", example: "Mi arrabbio quando le cose non funzionano.", tag: "emotions" },
  { it: "commuoversi", en: "to be moved (emotionally)", example: "Mi sono commosso guardando quel film.", tag: "emotions" },
  // ─── Shopping & Errands
  { it: "lo scontrino", en: "the receipt", example: "Hai tenuto lo scontrino?", tag: "shopping" },
  { it: "il camerino", en: "the fitting room", example: "Posso provare questa maglia in camerino?", tag: "shopping" },
  { it: "la taglia", en: "the size (clothing)", example: "Che taglia porti?", tag: "shopping" },
  { it: "provare", en: "to try on", example: "Vorrei provare queste scarpe.", tag: "shopping" },
  { it: "il reso", en: "the return (of goods)", example: "Vorrei fare un reso, il prodotto è difettoso.", tag: "shopping" },
  { it: "fare la fila", en: "to stand in line / to queue", example: "Ho fatto la fila per mezz'ora.", tag: "shopping" },
  { it: "il centro commerciale", en: "the shopping mall", example: "Andiamo al centro commerciale sabato?", tag: "shopping" },
  { it: "lo sconto", en: "the discount", example: "C'è uno sconto del venti per cento.", tag: "shopping" },
  { it: "il prezzo", en: "the price", example: "Il prezzo mi sembra un po' alto.", tag: "shopping" },
  { it: "il contante", en: "cash", example: "Preferisco pagare in contante.", tag: "shopping" },
  { it: "la carta di credito", en: "the credit card", example: "Accettate la carta di credito?", tag: "shopping" },
  { it: "pagare alla cassa", en: "to pay at the register", example: "Puoi pagare alla cassa laggiù.", tag: "shopping" },
  // ─── Home & Living
  { it: "traslocare", en: "to move (house)", example: "Trasloco il mese prossimo.", tag: "home" },
  { it: "l'affitto", en: "the rent", example: "L'affitto è aumentato quest'anno.", tag: "home" },
  { it: "il coinquilino", en: "the roommate", example: "Il mio coinquilino è molto ordinato.", tag: "home" },
  { it: "i lavori di casa", en: "housework", example: "Ci dividiamo i lavori di casa.", tag: "home" },
  { it: "fare il bucato", en: "to do the laundry", example: "Devo fare il bucato oggi.", tag: "home" },
  { it: "stirare", en: "to iron", example: "Odio stirare le camicie.", tag: "home" },
  { it: "passare l'aspirapolvere", en: "to vacuum", example: "Passo l'aspirapolvere due volte a settimana.", tag: "home" },
  { it: "il piano", en: "the floor (of a building)", example: "Abito al terzo piano.", tag: "home" },
  { it: "le bollette", en: "the bills (utilities)", example: "Le bollette sono arrivate ieri.", tag: "home" },
  { it: "arredare", en: "to furnish / to decorate", example: "Ho arredato il salotto in stile moderno.", tag: "home" },
  { it: "il quartiere", en: "the neighborhood", example: "Il mio quartiere è molto tranquillo.", tag: "home" },
  { it: "il vicino di casa", en: "the neighbor", example: "Il vicino di casa è molto gentile.", tag: "home" },
  // ─── Weather & Nature
  { it: "il temporale", en: "the thunderstorm", example: "Sta arrivando un temporale.", tag: "weather" },
  { it: "la grandine", en: "the hail", example: "La grandine ha danneggiato le macchine.", tag: "weather" },
  { it: "nevicare", en: "to snow", example: "Ha nevicato tutta la notte.", tag: "weather" },
  { it: "il vento forte", en: "strong wind", example: "Oggi c'è un vento forte incredibile.", tag: "weather" },
  { it: "l'afa", en: "the muggy heat / humidity", example: "Non sopporto l'afa estiva.", tag: "weather" },
  { it: "umido", en: "humid / damp", example: "Il clima qui è molto umido.", tag: "weather" },
  { it: "sereno", en: "clear (sky)", example: "Domani sarà sereno tutto il giorno.", tag: "weather" },
  { it: "nuvoloso", en: "cloudy", example: "Il cielo è nuvoloso ma non piove.", tag: "weather" },
  { it: "la previsione del tempo", en: "the weather forecast", example: "Hai visto la previsione del tempo?", tag: "weather" },
  { it: "il tramonto", en: "the sunset", example: "Il tramonto sul mare è bellissimo.", tag: "weather" },
  // ─── Social Life
  { it: "fare un aperitivo", en: "to have an aperitivo", example: "Facciamo un aperitivo dopo il lavoro?", tag: "social" },
  { it: "brindare", en: "to toast / to clink glasses", example: "Brindiamo al nuovo anno!", tag: "social" },
  { it: "organizzare una festa", en: "to organize a party", example: "Voglio organizzare una festa per il mio compleanno.", tag: "social" },
  { it: "invitare", en: "to invite", example: "Ti invito a cena sabato sera.", tag: "social" },
  { it: "rifiutare un invito", en: "to decline an invitation", example: "Mi dispiace, devo rifiutare l'invito.", tag: "social" },
  { it: "fare tardi", en: "to stay out late", example: "Ieri sera ho fatto tardi.", tag: "social" },
  { it: "annoiarsi", en: "to be bored", example: "Mi annoio quando non ho niente da fare.", tag: "social" },
  { it: "divertirsi", en: "to have fun", example: "Mi sono divertito moltissimo alla festa.", tag: "social" },
  { it: "il passatempo", en: "the hobby / pastime", example: "Il mio passatempo preferito è leggere.", tag: "social" },
  { it: "il pettegolezzo", en: "the gossip", example: "Non mi piacciono i pettegolezzi.", tag: "social" },
  { it: "il gossip", en: "gossip (informal)", example: "Hai sentito l'ultimo gossip?", tag: "social" },
  { it: "fare due chiacchiere", en: "to have a chat", example: "Facciamo due chiacchiere davanti a un caffè.", tag: "social" },
  // ─── Health & Body
  { it: "il mal di testa", en: "the headache", example: "Ho un mal di testa terribile.", tag: "health" },
  { it: "la febbre", en: "the fever", example: "Ho la febbre a trentotto.", tag: "health" },
  { it: "il raffreddore", en: "the cold (illness)", example: "Ho preso un raffreddore.", tag: "health" },
  { it: "la ricetta medica", en: "the prescription", example: "Il dottore mi ha dato la ricetta medica.", tag: "health" },
  { it: "la farmacia", en: "the pharmacy", example: "Devo passare in farmacia.", tag: "health" },
  { it: "lo sciroppo", en: "the syrup (medicine)", example: "Prendo lo sciroppo per la tosse.", tag: "health" },
  { it: "sentirsi male", en: "to feel sick", example: "Mi sento male, forse ho mangiato troppo.", tag: "health" },
  { it: "guarire", en: "to heal / to recover", example: "Ci vuole tempo per guarire.", tag: "health" },
  { it: "il pronto soccorso", en: "the emergency room", example: "Siamo andati al pronto soccorso.", tag: "health" },
  { it: "la visita medica", en: "the medical check-up", example: "Ho una visita medica domani.", tag: "health" },
  { it: "la puntura", en: "the injection / shot", example: "Ho paura delle punture.", tag: "health" },
  { it: "allergico", en: "allergic", example: "Sono allergico al polline.", tag: "health" },
  // ─── Media & Entertainment
  { it: "il telegiornale", en: "the TV news", example: "Guardo il telegiornale ogni sera.", tag: "media" },
  { it: "il documentario", en: "the documentary", example: "Ho visto un documentario interessantissimo.", tag: "media" },
  { it: "la serie tv", en: "the TV series", example: "Sto guardando una nuova serie tv.", tag: "media" },
  { it: "il personaggio", en: "the character", example: "Il personaggio principale è molto complesso.", tag: "media" },
  { it: "la trama", en: "the plot", example: "La trama del film è avvincente.", tag: "media" },
  { it: "il regista", en: "the director (film)", example: "Chi è il regista di questo film?", tag: "media" },
  { it: "lo spettacolo", en: "the show / performance", example: "Lo spettacolo è stato emozionante.", tag: "media" },
  { it: "il palcoscenico", en: "the stage", example: "Gli attori sono saliti sul palcoscenico.", tag: "media" },
  { it: "recitare", en: "to act / to perform", example: "Ha recitato in molti film famosi.", tag: "media" },
  { it: "il concerto", en: "the concert", example: "Andiamo al concerto stasera?", tag: "media" },
  // ─── Bureaucracy & Documents
  { it: "il documento", en: "the document / ID", example: "Ha un documento di identità?", tag: "bureaucracy" },
  { it: "la carta d'identità", en: "the ID card", example: "La mia carta d'identità è scaduta.", tag: "bureaucracy" },
  { it: "il permesso di soggiorno", en: "the residence permit", example: "Devo rinnovare il permesso di soggiorno.", tag: "bureaucracy" },
  { it: "compilare un modulo", en: "to fill out a form", example: "Devi compilare questo modulo.", tag: "bureaucracy" },
  { it: "la firma", en: "the signature", example: "Metta la firma qui in basso.", tag: "bureaucracy" },
  { it: "il timbro", en: "the stamp (official)", example: "Serve il timbro dell'ufficio.", tag: "bureaucracy" },
  { it: "lo sportello", en: "the counter / window (office)", example: "Si rivolga allo sportello numero tre.", tag: "bureaucracy" },
  { it: "la pratica", en: "the paperwork / application", example: "La pratica è ancora in lavorazione.", tag: "bureaucracy" },
  { it: "l'appuntamento", en: "the appointment", example: "Ho preso un appuntamento per domani.", tag: "bureaucracy" },
  { it: "la scadenza del documento", en: "the document expiry date", example: "Controlla la scadenza del documento.", tag: "bureaucracy" },
  // ─── Slang & Informal
  { it: "una fregatura", en: "a rip-off / a scam", example: "Quel negozio è una fregatura!", tag: "slang" },
  { it: "sgamare", en: "to catch / to bust (slang)", example: "Mi hanno sgamato mentre copiavo.", tag: "slang" },
  { it: "beccarsi", en: "to catch / to get (slang)", example: "Mi sono beccato un raffreddore.", tag: "slang" },
  { it: "mollare", en: "to dump / to give up", example: "Ha mollato il lavoro da un giorno all'altro.", tag: "slang" },
  { it: "fregarsene", en: "to not give a damn", example: "Me ne frego di quello che pensano.", tag: "slang" },
  { it: "sbattere", en: "to slam / to bother (slang)", example: "Non mi va di sbattermi per niente.", tag: "slang" },
  { it: "scocciare", en: "to annoy / to bother", example: "Smettila di scocciare, sto lavorando.", tag: "slang" },
  { it: "spaccare", en: "to rock / to crush it (slang)", example: "Quel concerto ha spaccato!", tag: "slang" },
  { it: "scherzare", en: "to joke", example: "Stavo solo scherzando, non arrabbiarti.", tag: "slang" },
  { it: "il casino", en: "the mess / chaos (slang)", example: "Che casino in questa stanza!", tag: "slang" },
];

export const seedCards = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("cards").take(1);
    if (existing.length > 0) {
      return { status: "already_seeded", count: 0 };
    }

    const today = new Date().toISOString().slice(0, 10);
    let count = 0;

    // Convex mutations have size limits, so batch in chunks
    for (const card of allVocab) {
      await ctx.db.insert("cards", {
        it: card.it,
        en: card.en,
        example: card.example,
        tag: card.tag,
        source: "builtin" as const,
        ease: 2.5,
        interval: 0,
        repetitions: 0,
        nextReview: today,
      });
      count++;
    }

    return { status: "seeded", count };
  },
});
